- source/hangman.js
> New hangman script.

- source/trainer-cards.js
Just a clean up and polishing of my card was wayy too big and annoying
> Clean Up of My Card

- source/trainer-cards.js
> Fixed my error

- source/trainer-cards.js
Gave Neith the first badge, Founder of Sora Badge
> Added the Badge System Yay

- source/custom-commands.js
> Fixed up Din Dins WILL WORK

- source/trainer-cards.js
> MAJOR BADGE IMPLEMENTATION

- source/trainer-cards.js
> Fixed Gasp's card and trialed a new badge display

- source/trainer-cards.js
Trialing a new card format for frontiers
> Update to my Card for trialing new format

- source/trainer-cards.js
Fixed Badges Card
Fixed Jeratt's Card
Fixed my card to Risu's Standards
> Implemented a few delayed fixes

- config/custom.css
> Revert "Update custom.css"

- source/trainer-cards.js
> Various fixes to various cards

- source/custom-commands.js
> Revert "New /regdate"

- commands.js
> Bringing back Declarered and Declaregreen

- commands.js
> fixing blade's mistake

- source/trainer-cards.js
> New quote for remy

- source/custom-commands.js
> Revert "Fixed stuff."

- config/config.js
> Revert "Should fix commands altogether"

- config/config.js
> Revert "Sigh if this doesnt work I cant do much"

- source/trainer-cards.js
> Revert "Added the last seen dates for all gym leaders."

- source/trainer-cards.js
revert revert revert revert revert
> Revert "Revert "Added the last seen dates for all gym leaders.""

- source/custom-commands.js
To admins (especially Noah): I edited the banlist filter. Read the comment in the code.
> Made and edited a few commands.
